### ISSUE TITLE
Make "ratio" the primary label for PATO:0001470 ! proportionality to

### ISSUE THREAD

**Issue by cmungall** [pato-ontology/pato#555]
```yaml
id: PATO:0001470
name: proportionality to
def: "A quality inhering in a bearer by virtue of the bearer's magnitude in respect to a related entity." [PATOC:nw]
synonym: "proportion" EXACT []
synonym: "proportionality" EXACT []
synonym: "quotient" EXACT []
synonym: "ratio" EXACT [] !! **make this the primary label**
synonym: "rate" RELATED []
is_a: PATO:0001018 ! physical quality
```
